//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsCollectorApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameClass", Namespace="http://schemas.datacontract.org/2004/07/RecordsCollectorApp")]
    [System.SerializableAttribute()]
    public partial class NameClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FemaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Female {
            get {
                return this.FemaleField;
            }
            set {
                if ((this.FemaleField.Equals(value) != true)) {
                    this.FemaleField = value;
                    this.RaisePropertyChanged("Female");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Male {
            get {
                return this.MaleField;
            }
            set {
                if ((this.MaleField.Equals(value) != true)) {
                    this.MaleField = value;
                    this.RaisePropertyChanged("Male");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberClass", Namespace="http://schemas.datacontract.org/2004/07/RecordsCollectorApp")]
    [System.SerializableAttribute()]
    public partial class NumberClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FemaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Female {
            get {
                return this.FemaleField;
            }
            set {
                if ((this.FemaleField.Equals(value) != true)) {
                    this.FemaleField = value;
                    this.RaisePropertyChanged("Female");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Male {
            get {
                return this.MaleField;
            }
            set {
                if ((this.MaleField.Equals(value) != true)) {
                    this.MaleField = value;
                    this.RaisePropertyChanged("Male");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="NamesService", ConfigurationName="ServiceReference1.DataBaseAccessService")]
    public interface DataBaseAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/LoadNameData", ReplyAction="NamesService/DataBaseAccessService/LoadNameDataResponse")]
        RecordsCollectorApp.ServiceReference1.NameClass LoadNameData(string Sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/UpdateNames", ReplyAction="NamesService/DataBaseAccessService/UpdateNamesResponse")]
        void UpdateNames(RecordsCollectorApp.ServiceReference1.NameClass NameObject, string Sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/LoadNumberData", ReplyAction="NamesService/DataBaseAccessService/LoadNumberDataResponse")]
        RecordsCollectorApp.ServiceReference1.NumberClass LoadNumberData(string Sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/UpdateNumbers", ReplyAction="NamesService/DataBaseAccessService/UpdateNumbersResponse")]
        void UpdateNumbers(RecordsCollectorApp.ServiceReference1.NumberClass NumberObject, string Sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/CountNamesRecords", ReplyAction="NamesService/DataBaseAccessService/CountNamesRecordsResponse")]
        int CountNamesRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="NamesService/DataBaseAccessService/CountNumbersRecords", ReplyAction="NamesService/DataBaseAccessService/CountNumbersRecordsResponse")]
        int CountNumbersRecords();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBaseAccessServiceChannel : RecordsCollectorApp.ServiceReference1.DataBaseAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBaseAccessServiceClient : System.ServiceModel.ClientBase<RecordsCollectorApp.ServiceReference1.DataBaseAccessService>, RecordsCollectorApp.ServiceReference1.DataBaseAccessService {
        
        public DataBaseAccessServiceClient() {
        }
        
        public DataBaseAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBaseAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RecordsCollectorApp.ServiceReference1.NameClass LoadNameData(string Sex) {
            return base.Channel.LoadNameData(Sex);
        }
        
        public void UpdateNames(RecordsCollectorApp.ServiceReference1.NameClass NameObject, string Sex) {
            base.Channel.UpdateNames(NameObject, Sex);
        }
        
        public RecordsCollectorApp.ServiceReference1.NumberClass LoadNumberData(string Sex) {
            return base.Channel.LoadNumberData(Sex);
        }
        
        public void UpdateNumbers(RecordsCollectorApp.ServiceReference1.NumberClass NumberObject, string Sex) {
            base.Channel.UpdateNumbers(NumberObject, Sex);
        }
        
        public int CountNamesRecords() {
            return base.Channel.CountNamesRecords();
        }
        
        public int CountNumbersRecords() {
            return base.Channel.CountNumbersRecords();
        }
    }
}
